services:
  mysql:
    image: mysql:8.4
    profiles: ["mysql"]
    container_name: sb-ecom-mysql
    environment:
      MYSQL_DATABASE: sb_ecom
      MYSQL_USER: sb_ecom
      MYSQL_PASSWORD: sb_ecom_pass
      MYSQL_ROOT_PASSWORD: root_pass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  postgres:
    image: postgres:17
    profiles: ["postgres"]
    container_name: sb-ecom-postgres
    environment:
      POSTGRES_DB: sb_ecom
      POSTGRES_USER: sb_ecom
      POSTGRES_PASSWORD: sb_ecom_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  mysql_data:
  postgres_data:
